cd /opt/c2k
docker compose -f docker-compose.prod.yml -f docker-compose.prod.vps.yml --env-file .env.production exec -T postgres psql -U c2k -d c2k -c "SELECT u.username, pp.sort_order, left(pp.url,50) AS url_prefix, pp.created_at FROM profile_photos pp JOIN profiles p ON p.id=pp.profile_id JOIN users u ON u.id=p.user_id ORDER BY pp.created_at DESC;"
docker compose -f docker-compose.prod.yml -f docker-compose.prod.vps.yml --env-file .env.production exec -T postgres psql -U c2k -d c2k -c "SELECT u.username, ma.id, ma.upload_status, ma.scan_status, ma.source_surface, ma.created_at FROM media_assets ma JOIN users u ON u.id=ma.uploader_user_id WHERE ma.upload_status IN ('REJECTED','QUARANTINED') OR ma.scan_status IN ('REJECTED','QUARANTINED','PENDING_SCAN') ORDER BY ma.created_at DESC LIMIT 20;"
docker compose -f docker-compose.prod.yml -f docker-compose.prod.vps.yml --env-file .env.production exec -T postgres psql -U c2k -d c2k -c "SELECT COUNT(*) AS brax_media FROM media_assets ma JOIN users u ON u.id=ma.uploader_user_id WHERE u.username='Brax';"
docker compose -f docker-compose.prod.yml -f docker-compose.prod.vps.yml --env-file .env.production exec -T postgres psql -U c2k -d c2k -c "SELECT pp.id, pp.sort_order, left(pp.url,70), pp.created_at FROM profile_photos pp JOIN profiles p ON p.id=pp.profile_id JOIN users u ON u.id=p.user_id WHERE u.username='Brax' ORDER BY pp.created_at;"
docker compose -f docker-compose.prod.yml -f docker-compose.prod.vps.yml --env-file .env.production exec -T postgres psql -U c2k -d c2k -c "SELECT u.username, COUNT(*) AS primary_count FROM profile_photos pp JOIN profiles p ON p.id=pp.profile_id JOIN users u ON u.id=p.user_id WHERE pp.sort_order = 0 GROUP BY u.username HAVING COUNT(*) > 1;"
docker compose -f docker-compose.prod.yml -f docker-compose.prod.vps.yml --env-file .env.production logs api --tail=12000 2>&1 | grep "request completed" | grep -E "/api/upload|/api/profile/me/photos" | grep -vE "statusCode\":20[01]" | tail -40
docker compose -f docker-compose.prod.yml -f docker-compose.prod.vps.yml --env-file .env.production logs api --tail=12000 2>&1 | grep -E "req-5r2|req-5rb|req-5rr|req-5rg|req-5rn|req-5rp|req-5qz" | tail -35
docker compose -f docker-compose.prod.yml -f docker-compose.prod.vps.yml --env-file .env.production logs worker --tail=300 2>&1 | grep -iE "error|fail|scan|quarantine|media" | tail -20
